[build]
  functions = "functions/"
  publish = "dist/"
  command = "export PATH=\"/opt/build/repo/bin:$PATH\" && echo $PATH && export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm install && npm run build"

[dev]
  command = "npm start"
  targetPort = 7373
  autoLaunch = true
  framework = "#custom"

